### ISSUE TITLE
"** Cannot check for duplicate keys in YAML header (undefined local variable or method `_1' for KramdownRFC::YAMLcheck:Module)"

### ISSUE THREAD

**Issue by richsalz** [cabo/kramdown-rfc#256]
I get this message with all my drafts lately...

**Comment by cabo** [comment]
Which Ruby version do you use?
Apparently I put in some code that only has been working in the last 10 years or so..

**Comment by cabo** [comment]
OK, _1 came in with Ruby 2.7 in December 2019.
I'll fix this so it still works with 2.6.

**Comment by cabo** [comment]
Thank you for this (and your other) report!

**Comment by richsalz** [comment]
i just use Martin's i-d-template repo.  /usr/bin/ruby says 2.6.10 but I don't know if venv or other things end up pointing to another instance somewhere else.
